FROM python:3.12

WORKDIR /app

COPY requirements.txt requirements.txt



RUN pip install -r requirements.txt


COPY . .

EXPOSE 8000

#python -m celery -A auth_service worker -l info"
CMD ["sh", "-c", "sleep 10 & python manage.py runserver 0.0.0.0:8000 & python -m celery -A auth_service worker -l info"]
