# Generated by Django 4.2 on 2023-12-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='establishment')),
                ('highest_authority', models.CharField(max_length=255)),
                ('first_name_authority', models.CharField(max_length=255)),
                ('last_name_authority', models.CharField(max_length=255)),
                ('job_authority', models.CharField(max_length=255)),
                ('email_authority', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LawEnforcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_committe', models.CharField(max_length=255)),
                ('first_name_committe', models.CharField(max_length=255)),
                ('last_name_committe', models.CharField(max_length=255)),
                ('job_committe', models.CharField(max_length=255)),
                ('email_committe', models.CharField(max_length=255)),
                ('establishment', models.ManyToManyField(to='app_admin.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='AccessToInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('establishment', models.ManyToManyField(to='app_admin.establishment')),
            ],
        ),
    ]
