# Generated by Django 4.2 on 2023-12-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoinformation',
            name='establishment',
            field=models.ManyToManyField(related_name='accesstoinformation_set', to='app_admin.establishment'),
        ),
        migrations.AlterField(
            model_name='lawenforcement',
            name='establishment',
            field=models.ManyToManyField(related_name='lawenforcement_set', to='app_admin.establishment'),
        ),
    ]
