# Generated by Django 4.2 on 2023-12-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_accesstoinformation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesstoinformation',
            options={'verbose_name': 'Acceso a la Información', 'verbose_name_plural': 'Accesos a la Información'},
        ),
        migrations.AlterModelOptions(
            name='establishment',
            options={'verbose_name': 'Institución', 'verbose_name_plural': 'Instituciones'},
        ),
        migrations.AlterModelOptions(
            name='lawenforcement',
            options={'verbose_name': 'Comité de Transparencia', 'verbose_name_plural': 'Comités de Transparencia'},
        ),
    ]
