# Generated by Django 4.2 on 2023-12-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_alter_accesstoinformation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('form_type', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('type_field', models.CharField(blank=True, choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Fecha'), ('file', 'Archivo'), ('select', 'Selección'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('textarea', 'Textarea')], max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Campo de Formulario',
                'verbose_name_plural': 'Campos de Formulario',
            },
        ),
    ]
