# Generated by Django 4.2 on 2023-12-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0005_formfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfields',
            name='type_field',
            field=models.CharField(blank=True, choices=[('text', 'Texto'), ('password', 'Contraseña'), ('email', 'Email'), ('tel', 'Teléfono'), ('number', 'Número'), ('date', 'Fecha'), ('file', 'Archivo'), ('select', 'Selección'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('textarea', 'Textarea')], max_length=255, null=True),
        ),
    ]
