# Generated by Django 4.2 on 2023-12-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0008_establishment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfields',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
