# Generated by Django 4.2 on 2023-12-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0009_formfields_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfields',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfields',
            name='permission_required',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
