# Generated by Django 4.2 on 2023-12-31 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app_admin', '0010_formfields_options_formfields_permission_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfields',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='formfields',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
