# Generated by Django 4.2 on 2024-01-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0012_userestablishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
