# Generated by Django 4.2 on 2024-01-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0016_accesstoinformation_ip_configuration_ip_email_ip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedagogyarea',
            options={'verbose_name': 'Area de Pedagogia', 'verbose_name_plural': 'Areas de Pedagogia'},
        ),
        migrations.AddField(
            model_name='establishment',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
