# Generated by Django 4.2 on 2024-04-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0018_establishment_address_typeorganization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='identification',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
