# Generated by Django 4.2 on 2024-07-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0019_establishment_identification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'permissions': (('can_view_configuration', 'Puede ver configuración'),), 'verbose_name': 'Configuración', 'verbose_name_plural': 'Configuraciones'},
        ),
        migrations.AddField(
            model_name='establishment',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
