# Generated by Django 4.2 on 2024-09-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0020_alter_configuration_options_establishment_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
