# Generated by Django 4.2 on 2024-09-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0021_establishment_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfields',
            name='helptext',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
