# Generated by Django 4.2 on 2024-11-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0022_formfields_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='extra_numerals',
            field=models.JSONField(blank=True, default=list, help_text='Campo para almacenar una lista de ids para extra_numerals'),
        ),
    ]
