# Generated by Django 4.2 on 2024-11-11 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0023_establishment_extra_numerals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='extra_numerals',
        ),
    ]
