version: '3'

services:
  auth_microservice:
    build:
      context: ./microservices/auth_service
      dockerfile: Dockerfile
    ports:
      - "8000"
    depends_on:
      - db_auth
    volumes:
      - ./microservices/auth_service:/app
    

    environment:
      - DB_HOST=db_auth
      - DB_NAME=auth_database
      - DB_USER=auth_user
      - DB_PASSWORD=auth_password

    networks:
      - auth_microservice_network
      

  db_auth:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_database
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password

    networks:
      - auth_microservice_network



  api_gateway:
    image: nginx:latest
    ports:
      - "8081:8001"
    volumes:
      - ./api-gateway/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./microservices/auth_service/static:/usr/src/app/static/
    depends_on:
      - auth_microservice
    networks:
      - auth_microservice_network

    

volumes:
  auth_microservice:

networks:
  auth_microservice_network:

