version: '3'

services:


  redis_db:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - pnt_network
      
  admin_microservice:
    build:
      context: ./microservices/admin_service
      dockerfile: Dockerfile
    ports:
      - "8001"
    depends_on:
      - db_auth
      - redis_db
      - auth_microservice
    volumes:
      - ./microservices/admin_service:/app

    environment:
      - DB_HOST=db_auth
      - DB_NAME=auth_database
      - DB_USER=auth_user
      - DB_PASSWORD=auth_password
      - CELERY_BROKER_URL=redis://redis_db:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_db:6379/0
      - FRONTEND_PASSWORD_CONFIRMATION_URL=http://44.221.168.184/auth/reset-password/:token
      - FRONTEND_ACTIVATE_ACCOUNT_URL=http://44.221.168.184/auth/activate-account/:uidb64/:token

    networks:
      - pnt_network
  auth_microservice:
    build:
      context: ./microservices/auth_service
      dockerfile: Dockerfile
    ports:
      - "8000"
    depends_on:
      - db_auth
      - redis_db
    volumes:
      - ./microservices/auth_service:/app
    

    environment:
      - DB_HOST=db_auth
      - DB_NAME=auth_database
      - DB_USER=auth_user
      - DB_PASSWORD=auth_password
      - CELERY_BROKER_URL=redis://redis_db:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_db:6379/0

    networks:
      - pnt_network


 
      

  db_auth:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_database
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password

    networks:
      - pnt_network


  mongo_db:
    image: mongo:latest
    networks:
      - pnt_network


  api_gateway:
    image: nginx:latest
    ports:
      - "8082:8001"
    volumes:
      - ./api-gateway/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./microservices/auth_service/static:/usr/src/app/static/
    depends_on:
      - auth_microservice
      - admin_microservice
    networks:
      - pnt_network

    

volumes:
  auth_microservice:
  admin_microservice:

networks:
  pnt_network:
    external: true
    name: pnt_network

