version: '3'

services:


  redis_db:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - pnt_network



  auth_microservice:
    build:
      context: ./microservices/auth_service
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    depends_on:
      - db_auth
      - redis_db
    volumes:
      - ./microservices/auth_service:/app


    environment:
      - DB_HOST=db_auth
      - DB_NAME=auth_database
      - DB_USER=auth_user
      - DB_PASSWORD=auth_password
      - CELERY_BROKER_URL=redis://redis_db:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_db:6379/0

    networks:
      - pnt_network

  


  admin_microservice:
    build:
      context: ./microservices/admin_service
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8001"
    depends_on:
      - db_auth
      - auth_microservice
      - redis_db
    volumes:
      - ./microservices/admin_service:/app

    environment:
      - DB_HOST=db_auth
      - DB_NAME=auth_database
      - DB_USER=auth_user
      - DB_PASSWORD=auth_password
      - CELERY_BROKER_URL=redis://redis_db:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_db:6379/0

    networks:
      - pnt_network
      

  db_auth:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: auth_database
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password

    networks:
      - pnt_network



  api_gateway:
    image: nginx:latest
    ports:
      - "8082:8001"
    volumes:
      - ./api-gateway/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./microservices/auth_service/static:/usr/src/app/static/
    depends_on:
      - auth_microservice
      - admin_microservice
    networks:
      - pnt_network


  

    

volumes:
  auth_microservice:
  admin_microservice:

networks:
  pnt_network:

