# Generated by Django 4.2 on 2023-12-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='type_person',
        ),
        migrations.AddField(
            model_name='person',
            name='accept_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='job',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='race',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
