# Generated by Django 4.2 on 2023-12-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_person_type_person_person_accept_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=255, null=True),
        ),
    ]
