# Generated by Django 4.2 on 2023-12-31 14:53

from django.db import migrations, models
import os

def create_procedure_auth_register(apps, schema_editor):

    sp_path = os.path.join(os.path.dirname(__file__), 'functions', 'auth_register_citizen_user.sql')
    sql = None
    with open(sp_path, 'r') as f:
        sql = f.read()
    
    # Ejecutar el SQL
    if sql is not None:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(sql)
    
    else:
        raise Exception('No se pudo leer el archivo SQL')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_person_country'),
    ]

    operations = [
        migrations.RunPython(create_procedure_auth_register),

    ]
