# Generated by Django 4.2 on 2024-01-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_create_procedure_auth_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
