# Generated by Django 4.2 on 2024-09-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='person',
            name='group_priority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
