# Generated by Django 4.2 on 2024-01-20 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0002_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepublication',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='typepublication',
            name='publication',
        ),
        migrations.AddField(
            model_name='publication',
            name='file_publication',
            field=models.ManyToManyField(blank=True, related_name='publication_file_publication', to='entity_app.filepublication'),
        ),
        migrations.AddField(
            model_name='publication',
            name='type_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_type_publication', to='entity_app.typepublication'),
        ),
    ]
