# Generated by Django 4.2 on 2024-01-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0003_remove_filepublication_publication_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filepublication',
            options={'verbose_name': 'Archivo Publicación', 'verbose_name_plural': 'Archivo Publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Etiqueta', 'verbose_name_plural': 'Etiquetas'},
        ),
        migrations.AlterModelOptions(
            name='typepublication',
            options={'verbose_name': 'Tipo de Publicación', 'verbose_name_plural': 'Tipos de Publicaciones'},
        ),
        migrations.AddField(
            model_name='typepublication',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
