# Generated by Django 4.2 on 2024-01-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0004_alter_filepublication_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEstablishmentExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'app_admin_user_establishment',
                'managed': False,
            },
        ),
    ]
