# Generated by Django 4.2 on 2024-01-21 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0005_userestablishmentextended'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userestablishmentextended',
            table='app_admin_userestablishment',
        ),
    ]
