# Generated by Django 4.2 on 2024-01-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0007_publication_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
