# Generated by Django 4.2 on 2024-02-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0011_columnfile_solicity_is_manual_templatefile_numeral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnfile',
            name='format',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='columnfile',
            name='regex',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='columnfile',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('file', 'File')], default='string', max_length=255),
        ),
    ]
