# Generated by Django 4.2 on 2024-02-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0012_columnfile_format_columnfile_regex_columnfile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transparencyactive',
            name='max_date_to_publish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transparencyactive',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transparencyactive',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transparencyactive',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('ingress', 'Ingresado')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='columnfile',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('file', 'File'), ('decimal', 'Decimal')], default='string', max_length=255),
        ),
    ]
