# Generated by Django 4.2 on 2024-02-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0013_transparencyactive_max_date_to_publish_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicity',
            old_name='title',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='solicity',
            name='user',
        ),
        migrations.AddField(
            model_name='solicity',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicity',
            name='first_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicity',
            name='format_receipt',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicity',
            name='identification',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicity',
            name='last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicity',
            name='phone',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicity',
            name='type_receipt',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
