# Generated by Django 4.2 on 2024-03-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0014_rename_title_solicity_address_remove_solicity_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='numeral',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
