# Generated by Django 4.2 on 2024-04-06 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity_app', '0016_transparencyfocal_transparencycolab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicity',
            old_name='identification',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='solicity',
            old_name='type_receipt',
            new_name='format_send',
        ),
        migrations.AddField(
            model_name='solicity',
            name='date',
            field=models.DateTimeField(
                default=datetime(2024, 4, 6, 20, 24, 47, 982000)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicity',
            name='gender',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicity',
            name='number_saip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solicity',
            name='race_identification',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extension',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREADO'), ('DRAFT', 'BORRADOR'), ('SEND', 'ENVIADO'), ('PENDING', 'PENDIENTE'), (
                'READING', 'LEÍDO'), ('PROCESSING', 'EN PROCESO'), ('FINISHED', 'FINALIZADO')], default='CREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='insistency',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREADO'), ('DRAFT', 'BORRADOR'), ('SEND', 'ENVIADO'), ('PENDING', 'PENDIENTE'), (
                'READING', 'LEÍDO'), ('PROCESSING', 'EN PROCESO'), ('FINISHED', 'FINALIZADO')], default='CREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='solicity',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREADO'), ('DRAFT', 'BORRADOR'), ('SEND', 'ENVIADO'), ('PENDING', 'PENDIENTE'), (
                'READING', 'LEÍDO'), ('PROCESSING', 'EN PROCESO'), ('FINISHED', 'FINALIZADO')], default='CREATED', max_length=10),
        ),
        migrations.CreateModel(
            name='TimeLineSolicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(
                    blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(
                    blank=True, default=None, null=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'CREADO'), ('DRAFT', 'BORRADOR'), ('SEND', 'ENVIADO'), ('PENDING', 'PENDIENTE'), (
                    'READING', 'LEÍDO'), ('PROCESSING', 'EN PROCESO'), ('FINISHED', 'FINALIZADO')], default='CREATED', max_length=10)),
                ('solicity', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='entity_app.solicity')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='%(class)s_user_deleted', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Solicitud',
                'verbose_name_plural': 'Historiales de Solicitudes',
            },
        ),
    ]
