# Generated by Django 4.2 on 2024-04-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0018_alter_solicity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelinesolicity',
            name='status',
            field=models.CharField(choices=[('SEND', 'ENVIADO'), ('PENDING', 'PENDIENTE'), ('RESPONSE', 'RESPUESTA'), ('INSISTENCY', 'INSISTENCIA'), ('PENDING_RESPONSE_INSISTENCY', 'PENDIENTE RESPUESTA INSISTENCIA'), ('RESPONSE_INSISTENCY', 'RESPUESTA INSISTENCIA'), ('INFORMAL_MANAGEMENT', 'GESTIÓN OFICIOSA')], default='PENDING', max_length=255),
        ),
    ]
