# Generated by Django 4.2 on 2024-04-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0019_alter_timelinesolicity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='numeral',
            name='type_transparency',
            field=models.CharField(choices=[('A', 'Activa'), ('P', 'Pasiva'), ('C', 'Colaborativa'), ('F', 'Focalizada')], default='A', max_length=255),
        ),
    ]
