# Generated by Django 4.2 on 2024-04-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0020_numeral_type_transparency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transparencycolab',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='transparencyfocal',
            unique_together=set(),
        ),
    ]
