# Generated by Django 4.2 on 2024-04-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0021_alter_transparencycolab_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicityresponse',
            name='category',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
