# Generated by Django 4.2 on 2024-04-18 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0022_alter_solicityresponse_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicityresponse',
            name='category',
        ),
    ]
