# Generated by Django 4.2 on 2024-04-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0023_remove_solicityresponse_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='entity_app.attachment'),
        ),
        migrations.AddField(
            model_name='extension',
            name='files',
            field=models.ManyToManyField(blank=True, to='entity_app.filepublication'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'BORRADOR'), ('SEND', 'ENVIADO'), ('RESPONSED', 'RESPONDIDA'), ('NO_RESPONSED', 'NO RESPONDIDA'), ('INSISTENCY_PERIOD', 'PERIODO DE INSISTENCIA'), ('INSISTENCY_SEND', 'INSISTENCIA ENVIADA'), ('INSISTENCY_RESPONSED', 'INSISTENCIA RESPONDIDA'), ('INSISTENCY_NO_RESPONSED', 'INSISTENCIA NO RESPONDIDA'), ('PERIOD_INFORMAL_MANAGEMENT', 'PERIODO DE GESTIÓN OFICIOSA'), ('INFORMAL_MANAGMENT_SEND', 'GESTIÓN OFICIOSA ENVIADA'), ('INFORMAL_MANAGMENT_RESPONSED', 'GESTIÓN OFICIOSA RESPONDIDA'), ('INFORMAL_MANAGMENT_NO_RESPONSED', 'GESTIÓN OFICIOSA NO RESPONDIDA'), ('FINISHED_WITHOUT_RESPONSE', 'FINALIZADO SIN RESPUESTA'), ('FINISHED', 'FINALIZADO')], default='SEND', max_length=50),
        ),
        migrations.AlterField(
            model_name='insistency',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'BORRADOR'), ('SEND', 'ENVIADO'), ('RESPONSED', 'RESPONDIDA'), ('NO_RESPONSED', 'NO RESPONDIDA'), ('INSISTENCY_PERIOD', 'PERIODO DE INSISTENCIA'), ('INSISTENCY_SEND', 'INSISTENCIA ENVIADA'), ('INSISTENCY_RESPONSED', 'INSISTENCIA RESPONDIDA'), ('INSISTENCY_NO_RESPONSED', 'INSISTENCIA NO RESPONDIDA'), ('PERIOD_INFORMAL_MANAGEMENT', 'PERIODO DE GESTIÓN OFICIOSA'), ('INFORMAL_MANAGMENT_SEND', 'GESTIÓN OFICIOSA ENVIADA'), ('INFORMAL_MANAGMENT_RESPONSED', 'GESTIÓN OFICIOSA RESPONDIDA'), ('INFORMAL_MANAGMENT_NO_RESPONSED', 'GESTIÓN OFICIOSA NO RESPONDIDA'), ('FINISHED_WITHOUT_RESPONSE', 'FINALIZADO SIN RESPUESTA'), ('FINISHED', 'FINALIZADO')], default='SEND', max_length=50),
        ),
        migrations.AlterField(
            model_name='solicity',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'BORRADOR'), ('SEND', 'ENVIADO'), ('RESPONSED', 'RESPONDIDA'), ('NO_RESPONSED', 'NO RESPONDIDA'), ('INSISTENCY_PERIOD', 'PERIODO DE INSISTENCIA'), ('INSISTENCY_SEND', 'INSISTENCIA ENVIADA'), ('INSISTENCY_RESPONSED', 'INSISTENCIA RESPONDIDA'), ('INSISTENCY_NO_RESPONSED', 'INSISTENCIA NO RESPONDIDA'), ('PERIOD_INFORMAL_MANAGEMENT', 'PERIODO DE GESTIÓN OFICIOSA'), ('INFORMAL_MANAGMENT_SEND', 'GESTIÓN OFICIOSA ENVIADA'), ('INFORMAL_MANAGMENT_RESPONSED', 'GESTIÓN OFICIOSA RESPONDIDA'), ('INFORMAL_MANAGMENT_NO_RESPONSED', 'GESTIÓN OFICIOSA NO RESPONDIDA'), ('FINISHED_WITHOUT_RESPONSE', 'FINALIZADO SIN RESPUESTA'), ('FINISHED', 'FINALIZADO')], default='DRAFT', max_length=50),
        ),
    ]
