# Generated by Django 4.2 on 2024-05-09 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0024_extension_attachments_extension_files_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establishmentextended',
            options={'managed': False, 'verbose_name': 'Institución', 'verbose_name_plural': 'Instituciones'},
        ),
        migrations.AddField(
            model_name='filepublication',
            name='file_join',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity_app.filepublication'),
        ),
        migrations.AddField(
            model_name='filepublication',
            name='is_colab',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
