# Generated by Django 4.2 on 2024-05-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0025_alter_establishmentextended_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicity',
            name='date_mail_send',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
