# Generated by Django 4.2 on 2024-10-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0026_solicity_date_mail_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnfile',
            name='value',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='extension',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'BORRADOR'), ('SEND', 'ENVIADO'), ('PRORROGA', 'PRORROGA'), ('RESPONSED', 'RESPONDIDA'), ('NO_RESPONSED', 'NO RESPONDIDA'), ('INSISTENCY_PERIOD', 'PERIODO DE INSISTENCIA'), ('INSISTENCY_SEND', 'INSISTENCIA ENVIADA'), ('INSISTENCY_RESPONSED', 'INSISTENCIA RESPONDIDA'), ('INSISTENCY_NO_RESPONSED', 'INSISTENCIA NO RESPONDIDA'), ('PERIOD_INFORMAL_MANAGEMENT', 'PERIODO DE GESTIÓN OFICIOSA'), ('INFORMAL_MANAGMENT_SEND', 'GESTIÓN OFICIOSA ENVIADA'), ('INFORMAL_MANAGMENT_RESPONSED', 'GESTIÓN OFICIOSA RESPONDIDA'), ('INFORMAL_MANAGMENT_NO_RESPONSED', 'GESTIÓN OFICIOSA NO RESPONDIDA'), ('FINISHED_WITHOUT_RESPONSE', 'FINALIZADO SIN RESPUESTA'), ('FINISHED', 'FINALIZADO')], default='SEND', max_length=50),
        ),
        migrations.AlterField(
            model_name='insistency',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'BORRADOR'), ('SEND', 'ENVIADO'), ('PRORROGA', 'PRORROGA'), ('RESPONSED', 'RESPONDIDA'), ('NO_RESPONSED', 'NO RESPONDIDA'), ('INSISTENCY_PERIOD', 'PERIODO DE INSISTENCIA'), ('INSISTENCY_SEND', 'INSISTENCIA ENVIADA'), ('INSISTENCY_RESPONSED', 'INSISTENCIA RESPONDIDA'), ('INSISTENCY_NO_RESPONSED', 'INSISTENCIA NO RESPONDIDA'), ('PERIOD_INFORMAL_MANAGEMENT', 'PERIODO DE GESTIÓN OFICIOSA'), ('INFORMAL_MANAGMENT_SEND', 'GESTIÓN OFICIOSA ENVIADA'), ('INFORMAL_MANAGMENT_RESPONSED', 'GESTIÓN OFICIOSA RESPONDIDA'), ('INFORMAL_MANAGMENT_NO_RESPONSED', 'GESTIÓN OFICIOSA NO RESPONDIDA'), ('FINISHED_WITHOUT_RESPONSE', 'FINALIZADO SIN RESPUESTA'), ('FINISHED', 'FINALIZADO')], default='SEND', max_length=50),
        ),
        migrations.AlterField(
            model_name='solicity',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'BORRADOR'), ('SEND', 'ENVIADO'), ('PRORROGA', 'PRORROGA'), ('RESPONSED', 'RESPONDIDA'), ('NO_RESPONSED', 'NO RESPONDIDA'), ('INSISTENCY_PERIOD', 'PERIODO DE INSISTENCIA'), ('INSISTENCY_SEND', 'INSISTENCIA ENVIADA'), ('INSISTENCY_RESPONSED', 'INSISTENCIA RESPONDIDA'), ('INSISTENCY_NO_RESPONSED', 'INSISTENCIA NO RESPONDIDA'), ('PERIOD_INFORMAL_MANAGEMENT', 'PERIODO DE GESTIÓN OFICIOSA'), ('INFORMAL_MANAGMENT_SEND', 'GESTIÓN OFICIOSA ENVIADA'), ('INFORMAL_MANAGMENT_RESPONSED', 'GESTIÓN OFICIOSA RESPONDIDA'), ('INFORMAL_MANAGMENT_NO_RESPONSED', 'GESTIÓN OFICIOSA NO RESPONDIDA'), ('FINISHED_WITHOUT_RESPONSE', 'FINALIZADO SIN RESPUESTA'), ('FINISHED', 'FINALIZADO')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='transparencyactive',
            name='status',
            field=models.CharField(choices=[('aproved', 'Aprobado'), ('rejected', 'Rechazado'), ('ingress', 'Ingresado')], default='ingress', max_length=255),
        ),
    ]
