# Generated by Django 4.2 on 2024-11-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0027_columnfile_value_alter_extension_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='numeral',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
