# Generated by Django 4.2 on 2024-11-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0028_numeral_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='insistency',
            name='files',
            field=models.ManyToManyField(blank=True, to='entity_app.filepublication'),
        ),
    ]
