# Generated by Django 4.2 on 2025-01-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0029_insistency_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnfile',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='columnfile',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='numeral',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='templatefile',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transparencyactive',
            name='month',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transparencyactive',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transparencycolab',
            name='month',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transparencycolab',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transparencyfocal',
            name='month',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transparencyfocal',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
    ]