# Generated by Django 4.2 on 2025-01-13 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity_app', '0031_anualreport_indexinformationclassified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionOrganizationExt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Función de Organización',
                'verbose_name_plural': 'Funciones de Organización',
                'db_table': 'app_admin_functionorganization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicityInforAnualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.IntegerField()),
                ('total', models.IntegerField()),
                ('total_response_to_10_days', models.IntegerField()),
                ('total_reponse_to_11_days', models.IntegerField()),
                ('total_response_plus_15_days', models.IntegerField()),
                ('total_no_response', models.IntegerField()),
                ('percent_response_to_10_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percent_reponse_to_11_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percent_response_plus_15_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percent_no_response', models.DecimalField(decimal_places=2, max_digits=5)),
                ('anual_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity_app.anualreport')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_deleted', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BaseModel',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='anualreport',
            name='solicity_infor_anual_report',
            field=models.ManyToManyField(blank=True, related_name='anual_report_solicity_infor_anual_report', to='entity_app.solicityinforanualreport'),
        ),
    ]
