# Generated by Django 4.2 on 2025-01-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0032_functionorganizationext_solicityinforanualreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anualreport',
            name='comment_aclaration',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anualreport',
            name='comment_aclaration_no_registered',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anualreport',
            name='description_activities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anualreport',
            name='description_organic_law_citizen_participation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anualreport',
            name='description_organic_law_national_system',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anualreport',
            name='description_programs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anualreport',
            name='description_quality_problems',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anualreport',
            name='description_rason_no_portal',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anualreport',
            name='norme_archive_utility',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
