# Generated by Django 4.2 on 2025-01-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0035_anualreport_have_responded_solicities_no_portal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anualreport',
            name='description_organic_law_contraloria',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anualreport',
            name='description_organic_law_public_service',
            field=models.TextField(blank=True),
        ),
    ]
