# Generated by Django 4.2 on 2025-01-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0036_alter_anualreport_description_organic_law_contraloria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pnt1_Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=50)),
                ('function', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('establishment_name', models.CharField(max_length=255)),
                ('art', models.CharField(max_length=255)),
                ('numeral', models.CharField(max_length=255)),
                ('enero', models.BooleanField()),
                ('febrero', models.BooleanField()),
                ('marzo', models.BooleanField()),
                ('abril', models.BooleanField()),
                ('mayo', models.BooleanField()),
                ('junio', models.BooleanField()),
                ('julio', models.BooleanField()),
                ('agosto', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pnt1_Colab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=50)),
                ('function', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('establishment_name', models.CharField(max_length=255)),
                ('art', models.CharField(max_length=255)),
                ('numeral', models.CharField(max_length=255)),
                ('enero', models.BooleanField()),
                ('febrero', models.BooleanField()),
                ('marzo', models.BooleanField()),
                ('abril', models.BooleanField()),
                ('mayo', models.BooleanField()),
                ('junio', models.BooleanField()),
                ('julio', models.BooleanField()),
                ('agosto', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pnt1_Focal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=50)),
                ('function', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('establishment_name', models.CharField(max_length=255)),
                ('art', models.CharField(max_length=255)),
                ('numeral', models.CharField(max_length=255)),
                ('enero', models.BooleanField()),
                ('febrero', models.BooleanField()),
                ('marzo', models.BooleanField()),
                ('abril', models.BooleanField()),
                ('mayo', models.BooleanField()),
                ('junio', models.BooleanField()),
                ('julio', models.BooleanField()),
                ('agosto', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pnt1_Pasive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=50)),
                ('function', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('establishment_name', models.CharField(max_length=255)),
                ('saip', models.CharField(max_length=255)),
                ('name_solicitant', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('date_response', models.DateField()),
                ('state', models.CharField(max_length=255)),
            ],
        ),
    ]
