# Generated by Django 4.2 on 2025-01-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0037_pnt1_active_pnt1_colab_pnt1_focal_pnt1_pasive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pnt1_Reservada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=50)),
                ('function', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('establishment_name', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=255)),
                ('theme', models.CharField(max_length=255)),
                ('base_legal', models.CharField(max_length=255)),
                ('date_classification', models.DateField()),
                ('period', models.CharField(max_length=255)),
                ('extension', models.BooleanField()),
                ('description', models.CharField(max_length=255)),
                ('date_extension', models.DateField()),
                ('period_extension', models.CharField(max_length=255)),
            ],
        ),
    ]
