# Generated by Django 4.2 on 2025-01-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0038_pnt1_reservada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnt1_reservada',
            name='function',
        ),
        migrations.RemoveField(
            model_name='pnt1_reservada',
            name='type',
        ),
        migrations.AlterField(
            model_name='pnt1_reservada',
            name='base_legal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pnt1_reservada',
            name='date_classification',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pnt1_reservada',
            name='extension',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pnt1_reservada',
            name='theme',
            field=models.TextField(),
        ),
    ]
