# Generated by Django 4.2 on 2025-01-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0039_remove_pnt1_reservada_function_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnt1_reservada',
            name='date_extension',
            field=models.CharField(max_length=255),
        ),
    ]
