# Generated by Django 4.2 on 2025-01-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0040_alter_pnt1_reservada_date_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnt1_pasive',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pnt1_pasive',
            name='date_response',
            field=models.CharField(max_length=255),
        ),
    ]
