# Generated by Django 4.2 on 2025-01-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0041_alter_pnt1_pasive_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexinformationclassified',
            name='amplation_effectuation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='indexinformationclassified',
            name='ampliation_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='indexinformationclassified',
            name='classification_date',
            field=models.CharField(max_length=255),
        ),
    ]
