# Generated by Django 4.2 on 2025-01-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0043_generalanualreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexinformationclassified',
            name='legal_basis',
            field=models.TextField(),
        ),
    ]
