# Generated by Django 4.2 on 2025-01-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0044_alter_indexinformationclassified_legal_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexinformationclassified',
            name='amplation_effectuation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indexinformationclassified',
            name='ampliation_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indexinformationclassified',
            name='ampliation_period_of_validity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indexinformationclassified',
            name='classification_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indexinformationclassified',
            name='period_of_validity',
            field=models.TextField(),
        ),
    ]
