# Generated by Django 4.2 on 2025-01-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0045_alter_indexinformationclassified_amplation_effectuation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexinformationclassified',
            name='topic',
            field=models.TextField(),
        ),
    ]
