# Generated by Django 4.2 on 2025-01-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0046_alter_indexinformationclassified_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anualreport',
            name='norme_archive_utility',
            field=models.TextField(blank=True),
        ),
    ]
